#!/bin/bash
  
#SBATCH --job-name=intensity
#SBATCH --output=intensity_outputs/intensity2.out

#SBATCH --cpus-per-task=10
#SBATCH --mem=10G
#SBATCH --gres=gpu:1

models=(
    'gru_thp_temporal_with_labels_adjust_param_nodiv'
    'gru_temporal_with_labels_gru_temporal_with_labels_thp-dd_separate_nodiv'

    'gru_sahp_temporal_with_labels_adjust_param'
    'gru_temporal_with_labels_gru_temporal_with_labels_sahp-dd_separate'

    'poisson_gru_mlp-cm_temporal_with_labels_adjust_param'
    'poisson_gru_temporal_with_labels_gru_temporal_with_labels_mlp-cm-dd_separate'

    'gru_log-normal-mixture_temporal_with_labels_adjust_param'
    'gru_temporal_with_labels_gru_temporal_with_labels_log-normal-mixture-dd_separate'

    'gru_rmtpp_temporal_with_labels_adjust_param'
    'gru_temporal_with_labels_gru_temporal_with_labels_rmtpp-dd_separate'
)

for model in ${models[@]}; do
    python3 -u intensity/plot_intensity.py \
    --dataset 'hawkes_exponential_mutual_large' \
    --load-from-dir 'data/baseline3' \
    --split 0 \
    --save-check-dir 'checkpoints/icml/hawkes_exponential_mutual_large' \
    --model-name $model \
    --batch-size 1 \
    --seed 2
done 